name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      # Instalar dependências do Node.js
      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'  # Certifique-se de usar a versão correta do Node.js para o seu projeto

      # Instalar as dependências do projeto
      - name: Install dependencies
        run: npm install

      # Instalar Angular CLI globalmente
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # Garantir permissão para executar o comando ng
      - name: Grant permission to run ng
        run: chmod +x ./node_modules/.bin/ng

      # Executar o build da aplicação Angular
      - name: Build the Angular app
        run: ng build --prod

      # Build e Deploy para o Azure Static Web Apps
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_MOSS_0CEDE0C1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist/hope" # Built app content directory - optional

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_MOSS_0CEDE0C1E }}
          action: "close"
